<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { useRouter } from 'vue-router'
import { Activity, Archive, ChevronRight, ClipboardList, FileText, Gauge, LogOut, Menu, Plus, Settings, Shield, Users, X } from 'lucide-vue-next'
import { ApiError, api, del, post, put } from '../../api'
import { useSessionStore } from '../../stores/session'
import type { ApplicationDetail, Application, Campaign, FormField, ReviewStatus, SiteContent } from '../../types'

type Tab='dashboard'|'applications'|'campaigns'|'content'|'admins'|'audit'
const router=useRouter(),session=useSessionStore(),tab=ref<Tab>('dashboard'),busy=ref(false),error=ref(''),menuOpen=ref(false)
const dashboard=ref<any>(null),campaigns=ref<Campaign[]>([]),applications=ref<Application[]>([]),content=ref<SiteContent|null>(null),admins=ref<any[]>([]),logs=ref<any[]>([])
const selectedCampaign=ref(0),statuses=ref<ReviewStatus[]>([]),fields=ref<FormField[]>([]),detail=ref<ApplicationDetail|null>(null),search=ref(''),note=ref('')
const fieldDraft=ref<FormField|null>(null),statusDraft=ref<ReviewStatus|null>(null),dialog=ref<'field'|'status'|null>(null)
const owner=computed(()=>session.isOwner), superAdmin=computed(()=>session.isSuperAdmin), selectedCampaignData=computed(()=>campaigns.value.find(c=>c.id===selectedCampaign.value))
const nav:[Tab,string,any][]=[['dashboard','总览',Gauge],['applications','报名管理',ClipboardList],['campaigns','批次与表单',Archive],['content','首页文案',FileText],['admins','用户管理',Users],['audit','审计日志',Activity]]

onMounted(async()=>{await session.checkAdmin();if(!session.admin){router.replace('/admin/login');return}await loadBase();await loadTab()})
watch(tab,()=>{menuOpen.value=false;error.value='';detail.value=null;loadTab()})
async function loadBase(){campaigns.value=(await api<{campaigns:Campaign[]}>('/admin/campaigns')).campaigns;selectedCampaign.value=selectedCampaign.value||campaigns.value[0]?.id||0}
async function loadTab(){try{if(tab.value==='dashboard')dashboard.value=await api('/admin/dashboard');if(tab.value==='applications')await loadApplications();if(tab.value==='campaigns')await loadCampaignConfig();if(tab.value==='content')content.value=(await api<{content:SiteContent}>('/admin/content')).content;if(tab.value==='admins'&&superAdmin.value)admins.value=(await api<{admins:any[]}>('/admin/admins')).admins;if(tab.value==='audit')logs.value=(await api<{logs:any[]}>('/admin/audit')).logs}catch(e){setError(e)}}
function setError(e:unknown){error.value=e instanceof ApiError?e.message:'操作失败，请重试'}
async function act(fn:()=>Promise<void>){error.value='';busy.value=true;try{await fn()}catch(e){setError(e)}finally{busy.value=false}}
async function logout(){await session.logout();router.replace('/admin/login')}
async function loadApplications(){applications.value=(await api<{applications:Application[]}>(`/admin/applications?campaignId=${selectedCampaign.value}&q=${encodeURIComponent(search.value)}`)).applications;statuses.value=(await api<{statuses:ReviewStatus[]}>(`/admin/campaigns/${selectedCampaign.value}/statuses`)).statuses}
async function loadCampaignConfig(){if(!selectedCampaign.value)return;[fields.value,statuses.value]=await Promise.all([api<{fields:FormField[]}>(`/admin/campaigns/${selectedCampaign.value}/fields`).then(r=>r.fields),api<{statuses:ReviewStatus[]}>(`/admin/campaigns/${selectedCampaign.value}/statuses`).then(r=>r.statuses)])}
async function openApplication(id:number){detail.value=await api<ApplicationDetail>(`/admin/applications/${id}`)}
async function changeStatus(statusId:number){if(!detail.value)return;await act(async()=>{await post(`/admin/applications/${detail.value!.application.id}/status`,{statusId});await openApplication(detail.value!.application.id);await loadApplications()})}
async function addNote(){if(!detail.value||!note.value.trim())return;await act(async()=>{await post(`/admin/applications/${detail.value!.application.id}/notes`,{content:note.value});note.value='';await openApplication(detail.value!.application.id)})}
function exportCsv(){window.location.href=`/api/v1/admin/export?campaignId=${selectedCampaign.value}`}
async function createCampaign(){const name=prompt('新批次名称，例如：2027 春季招新');if(!name)return;const slug=prompt('英文标识，例如：2027-spring');if(!slug)return;await act(async()=>{await post('/admin/campaigns',{name,slug});await loadBase();await loadTab()})}
async function cloneCampaign(){const name=prompt('复制后的批次名称');if(!name)return;const slug=prompt('新批次英文标识');if(!slug)return;await act(async()=>{await post(`/admin/campaigns/${selectedCampaign.value}/clone`,{name,slug});await loadBase()})}
async function editCampaign(){const c=selectedCampaignData.value;if(!c)return;const name=prompt('批次名称',c.name);if(!name)return;const slug=prompt('英文标识',c.slug);if(!slug)return;const startsAt=prompt('开放时间（RFC3339，可留空）',c.startsAt||'')||null;const endsAt=prompt('截止时间（RFC3339，可留空）',c.endsAt||'')||null;await act(async()=>{await put(`/admin/campaigns/${c.id}`,{name,slug,startsAt,endsAt});await loadBase()})}
async function toggleCampaign(){const c=selectedCampaignData.value;if(!c)return;await act(async()=>{if(c.status==='open')await post(`/admin/campaigns/${c.id}/close`);else await post(`/admin/campaigns/${c.id}/open`);await loadBase();await loadCampaignConfig()})}
async function archiveCampaign(){const c=selectedCampaignData.value;if(!c||!confirm(`归档“${c.name}”？归档后仍可查询历史报名。`))return;await act(async()=>{await post(`/admin/campaigns/${c.id}/archive`);await loadBase();await loadCampaignConfig()})}
function editField(field?:FormField){fieldDraft.value=field?JSON.parse(JSON.stringify(field)):{id:0,key:'',label:'',type:'text',required:false,placeholder:'',helpText:'',options:[],position:(fields.value.length+1)*10,validation:{}};dialog.value='field'}
async function saveField(){if(!fieldDraft.value)return;await act(async()=>{await post(`/admin/campaigns/${selectedCampaign.value}/fields`,fieldDraft.value);dialog.value=null;await loadCampaignConfig()})}
async function removeField(id:number){if(!confirm('确定删除该字段？'))return;await act(async()=>{await del(`/admin/campaigns/${selectedCampaign.value}/fields/${id}`);await loadCampaignConfig()})}
function editStatus(status?:ReviewStatus){statusDraft.value=status?JSON.parse(JSON.stringify(status)):{id:0,name:'',color:'#c5e801',description:'',position:(statuses.value.length+1)*10,isDefault:false};dialog.value='status'}
async function saveStatus(){if(!statusDraft.value)return;await act(async()=>{await post(`/admin/campaigns/${selectedCampaign.value}/statuses`,statusDraft.value);dialog.value=null;await loadCampaignConfig()})}
async function removeStatus(id:number){if(!confirm('确定删除该状态？'))return;await act(async()=>{await del(`/admin/campaigns/${selectedCampaign.value}/statuses/${id}`);await loadCampaignConfig()})}
async function saveContent(){if(!content.value)return;await act(async()=>{await put('/admin/content',content.value!);alert('首页文案已保存')})}
async function createAdmin(){const email=prompt('后台用户邮箱');if(!email)return;const password=prompt('初始密码（至少 8 位）');if(!password)return;const role=confirm('赋予“可编辑”权限？\n确定 = 可编辑，取消 = 仅查看')?'owner':'readonly';await act(async()=>{await post('/admin/admins',{email,password,role});admins.value=(await api<{admins:any[]}>('/admin/admins')).admins})}
async function updateAdmin(item:any){await act(async()=>{await put(`/admin/admins/${item.id}`,{role:item.role,active:item.active});admins.value=(await api<{admins:any[]}>('/admin/admins')).admins})}
</script>

<template>
  <div v-if="session.admin" class="admin-shell">
    <aside :class="['admin-sidebar',{open:menuOpen}]"><div class="admin-brand"><div class="brand"><span>IT</span><strong>STUDIO</strong></div><button @click="menuOpen=false"><X/></button></div><p class="admin-role"><Shield/> {{ superAdmin?'SUPER ADMIN':session.admin.role==='owner'?'EDIT ACCESS':'VIEW ONLY' }}</p><nav><button v-for="[key,label,Icon] in nav" v-show="key!=='admins'||superAdmin" :key="key" :class="{active:tab===key}" @click="tab=key"><component :is="Icon"/>{{ label }}<ChevronRight/></button></nav><div class="admin-user"><span>{{ session.admin.email }}</span><button @click="logout"><LogOut/> 退出</button></div></aside>
    <main class="admin-main">
      <header class="admin-topbar"><button class="admin-menu" @click="menuOpen=true"><Menu/></button><div><span>IT STUDIO / OPERATIONS</span><h1>{{ nav.find(n=>n[0]===tab)?.[1] }}</h1></div><time>{{ new Date().toLocaleDateString('zh-CN') }}</time></header>
      <p v-if="error" class="form-message error admin-error">{{ error }}</p>

      <section v-if="tab==='dashboard'&&dashboard" class="admin-section">
        <div class="metric-grid"><article><span>CAMPAIGNS</span><b>{{ dashboard.totals.campaigns }}</b><p>累计招新批次</p></article><article><span>APPLICATIONS</span><b>{{ dashboard.totals.applications }}</b><p>累计提交版本</p></article><article class="accent"><span>ACTIVE</span><b>{{ dashboard.totals.active }}</b><p>当前有效报名</p></article></div>
        <div class="admin-card"><div class="card-heading"><h2>批次概览</h2><span>LIVE DATABASE</span></div><table><thead><tr><th>批次</th><th>全部版本</th><th>有效报名</th></tr></thead><tbody><tr v-for="c in dashboard.campaigns" :key="c.id"><td>{{ c.name }}</td><td>{{ c.total }}</td><td>{{ c.active }}</td></tr></tbody></table></div>
      </section>

      <section v-if="tab==='applications'" class="admin-section">
        <div class="toolbar"><select v-model="selectedCampaign" @change="loadApplications"><option v-for="c in campaigns" :key="c.id" :value="c.id">{{ c.name }}</option></select><input v-model="search" placeholder="搜索学号或邮箱" @keyup.enter="loadApplications"/><button @click="loadApplications">查询</button><button @click="exportCsv">导出 CSV</button></div>
        <div class="split-admin"><div class="admin-card list-card"><div class="card-heading"><h2>报名列表</h2><span>{{ applications.length }} RECORDS</span></div><button v-for="a in applications" :key="a.id" class="application-row" :class="{selected:detail?.application.id===a.id}" @click="openApplication(a.id)"><div><b>{{ a.studentId }}</b><span>{{ a.email }}</span></div><i :style="{background:a.reviewStatus?.color}"/><span>{{ a.reviewStatus?.name }}</span><small>REV.{{ a.revision }}</small></button><p v-if="!applications.length" class="empty-hint">暂无匹配报名。</p></div>
          <div class="admin-card detail-card"><template v-if="detail"><div class="card-heading"><div><span>APPLICATION DETAIL</span><h2>{{ detail.application.studentId }}</h2></div><b>{{ detail.application.systemStatus==='submitted'?'有效报名':'已撤回' }}</b></div><label>审核状态<select :value="detail.application.reviewStatus?.id" :disabled="!owner" @change="changeStatus(Number(($event.target as HTMLSelectElement).value))"><option v-for="s in statuses" :key="s.id" :value="s.id">{{ s.name }}</option></select></label><dl class="admin-answers"><template v-for="a in detail.answers" :key="a.key"><dt>{{ a.label }}</dt><dd>{{ Array.isArray(a.value)?a.value.join('、'):a.value }}</dd></template><template v-for="u in detail.uploads" :key="u.id"><dt>{{ u.label }}</dt><dd><a :href="`/api/v1/admin/applications/${detail.application.id}/uploads/${u.id}`" target="_blank">查看 {{ u.name }}</a></dd></template></dl><div class="notes"><h3>内部备注</h3><article v-for="n in detail.notes as any[]" :key="n.id"><p>{{ n.content }}</p><small>{{ n.admin }} · {{ new Date(n.createdAt).toLocaleString('zh-CN') }}</small></article><form v-if="owner" @submit.prevent="addNote"><textarea v-model="note" placeholder="添加仅管理员可见的备注"/><button>添加备注</button></form></div></template><div v-else class="detail-placeholder"><ClipboardList/><p>选择一条报名查看完整内容</p></div></div>
        </div>
      </section>

      <section v-if="tab==='campaigns'" class="admin-section">
        <div class="toolbar"><select v-model="selectedCampaign" @change="loadCampaignConfig"><option v-for="c in campaigns" :key="c.id" :value="c.id">{{ c.name }} / {{ c.status }}</option></select><button v-if="owner" @click="createCampaign"><Plus/> 新建批次</button><button v-if="owner" @click="editCampaign">编辑批次</button><button v-if="owner" @click="cloneCampaign">复制当前批次</button><button v-if="owner&&selectedCampaignData?.status!=='archived'" :class="{danger:selectedCampaignData?.status==='open'}" @click="toggleCampaign">{{ selectedCampaignData?.status==='open'?'关闭招新':'开放招新' }}</button><button v-if="owner&&['draft','closed'].includes(selectedCampaignData?.status||'')" @click="archiveCampaign">归档</button></div>
        <div v-if="selectedCampaignData" class="campaign-banner"><div><span>CAMPAIGN / {{ selectedCampaignData.id }}</span><h2>{{ selectedCampaignData.name }}</h2></div><div><b>{{ selectedCampaignData.status.toUpperCase() }}</b><small>{{ selectedCampaignData.formLocked?'表单结构已永久锁定':'表单仍可编辑' }}</small></div></div>
        <div class="config-grid"><div class="admin-card"><div class="card-heading"><h2>动态表单</h2><button v-if="owner&&!selectedCampaignData?.formLocked" @click="editField()"><Plus/> 字段</button></div><div v-for="f in fields" :key="f.id" class="config-row"><span>{{ String(f.position).padStart(2,'0') }}</span><div><b>{{ f.label }}</b><small>{{ f.key }} / {{ f.type }} {{ f.required?'· 必填':'' }}</small></div><button v-if="owner&&!selectedCampaignData?.formLocked" @click="editField(f)">编辑</button><button v-if="owner&&!selectedCampaignData?.formLocked" @click="removeField(f.id)">删除</button></div></div>
          <div class="admin-card"><div class="card-heading"><h2>审核状态</h2><button v-if="owner" @click="editStatus()"><Plus/> 状态</button></div><div v-for="s in statuses" :key="s.id" class="config-row"><i :style="{background:s.color}"/><div><b>{{ s.name }} <em v-if="s.isDefault">默认</em></b><small>{{ s.description }}</small></div><button v-if="owner" @click="editStatus(s)">编辑</button><button v-if="owner&&!s.isDefault" @click="removeStatus(s.id)">删除</button></div></div></div>
      </section>

      <section v-if="tab==='content'&&content" class="admin-section"><div class="content-editor admin-card"><div class="card-heading"><div><span>FIXED CONTENT SLOTS</span><h2>首页文案</h2></div><button v-if="owner" class="accent-button" :disabled="busy" @click="saveContent">保存并发布</button></div><div class="editor-grid"><label>首屏眉题<input v-model="content.heroEyebrow" :disabled="!owner"/></label><label>首屏主标题<input v-model="content.heroTitle" :disabled="!owner"/></label><label class="wide">首屏副标题<textarea v-model="content.heroSubtitle" :disabled="!owner"/></label><label class="wide">宣言标题<textarea v-model="content.manifestoTitle" :disabled="!owner"/></label><label class="wide">宣言正文<textarea v-model="content.manifestoBody" :disabled="!owner"/></label></div><h3>方向卡片 / 4 SLOTS</h3><div class="repeater-grid"><article v-for="(item,i) in content.directions" :key="i"><input v-model="item.label" :disabled="!owner"/><input v-model="item.title" :disabled="!owner"/><textarea v-model="item.body" :disabled="!owner"/></article></div><h3>价值主张 / 3 SLOTS</h3><div class="repeater-grid"><article v-for="(item,i) in content.values" :key="i"><input v-model="item.label" :disabled="!owner"/><input v-model="item.title" :disabled="!owner"/><textarea v-model="item.body" :disabled="!owner"/></article></div><h3>招新流程 / 4 SLOTS</h3><div class="repeater-grid"><article v-for="(item,i) in content.process" :key="i"><input v-model="item.label" :disabled="!owner"/><input v-model="item.title" :disabled="!owner"/><textarea v-model="item.body" :disabled="!owner"/></article></div><h3>FAQ / 3 SLOTS</h3><div class="repeater-grid"><article v-for="(item,i) in content.faqs" :key="i"><input v-model="item.label" :disabled="!owner"/><input v-model="item.title" :disabled="!owner"/><textarea v-model="item.body" :disabled="!owner"/></article></div><div class="editor-grid"><label>结尾标题<input v-model="content.contactTitle" :disabled="!owner"/></label><label>联系链接<input v-model="content.contactLink" :disabled="!owner"/></label><label class="wide">结尾文案<textarea v-model="content.contactBody" :disabled="!owner"/></label></div></div></section>

      <section v-if="tab==='admins'&&superAdmin" class="admin-section"><div class="admin-card"><div class="card-heading"><div><span>SUPERADMIN ONLY / ACCESS CONTROL</span><h2>后台用户管理</h2></div><button @click="createAdmin"><Plus/> 添加用户</button></div><p class="access-hint">超级管理员由环境变量初始化且不可降级；可编辑用户能处理报名、批次和文案，但不能管理后台用户；仅查看用户不能执行写操作。</p><table><thead><tr><th>邮箱</th><th>权限</th><th>状态</th><th>创建时间</th><th/></tr></thead><tbody><tr v-for="a in admins" :key="a.id"><td>{{ a.email }} <em v-if="a.isSuperAdmin" class="super-badge">超级管理员</em></td><td><select v-model="a.role" :disabled="a.isSuperAdmin"><option value="owner">可编辑</option><option value="readonly">仅查看</option></select></td><td><label class="switch"><input v-model="a.active" type="checkbox" :disabled="a.isSuperAdmin"/><span/></label></td><td>{{ new Date(a.createdAt).toLocaleDateString('zh-CN') }}</td><td><button v-if="!a.isSuperAdmin" @click="updateAdmin(a)">保存</button><span v-else>ENV LOCKED</span></td></tr></tbody></table></div></section>
      <section v-if="tab==='audit'" class="admin-section"><div class="admin-card"><div class="card-heading"><div><span>IMMUTABLE TRAIL</span><h2>最近 300 条操作</h2></div></div><table><thead><tr><th>时间</th><th>操作者</th><th>动作</th><th>对象</th></tr></thead><tbody><tr v-for="l in logs" :key="l.id"><td>{{ new Date(l.createdAt).toLocaleString('zh-CN') }}</td><td>{{ l.actorType }} #{{ l.actorId }}</td><td>{{ l.action }}</td><td>{{ l.entityType }} #{{ l.entityId }}</td></tr></tbody></table></div></section>
    </main>

    <div v-if="dialog" class="modal-backdrop" @click.self="dialog=null"><form v-if="dialog==='field'&&fieldDraft" class="admin-modal" @submit.prevent="saveField"><div class="card-heading"><h2>{{ fieldDraft.id?'编辑字段':'新增字段' }}</h2><button type="button" @click="dialog=null"><X/></button></div><label>字段标识<input v-model="fieldDraft.key" required pattern="[a-z0-9-]+"/></label><label>显示名称<input v-model="fieldDraft.label" required/></label><label>类型<select v-model="fieldDraft.type"><option v-for="t in ['text','textarea','number','date','url','radio','checkbox','select','image']" :key="t">{{ t }}</option></select></label><label>占位提示<input v-model="fieldDraft.placeholder"/></label><label>帮助文字<input v-model="fieldDraft.helpText"/></label><label v-if="['radio','checkbox','select'].includes(fieldDraft.type)">选项（每行一个）<textarea :value="fieldDraft.options.join('\n')" @input="fieldDraft!.options=($event.target as HTMLTextAreaElement).value.split('\n').filter(Boolean)"/></label><label>排序值<input v-model.number="fieldDraft.position" type="number"/></label><label class="agreement"><input v-model="fieldDraft.required" type="checkbox"/> 必填字段</label><button class="primary-btn" :disabled="busy">保存字段</button></form>
      <form v-if="dialog==='status'&&statusDraft" class="admin-modal" @submit.prevent="saveStatus"><div class="card-heading"><h2>{{ statusDraft.id?'编辑状态':'新增状态' }}</h2><button type="button" @click="dialog=null"><X/></button></div><label>状态名称<input v-model="statusDraft.name" required/></label><label>颜色<input v-model="statusDraft.color" type="color"/></label><label>学生可见说明<textarea v-model="statusDraft.description"/></label><label>排序值<input v-model.number="statusDraft.position" type="number"/></label><label class="agreement"><input v-model="statusDraft.isDefault" type="checkbox"/> 新报名默认状态</label><button class="primary-btn" :disabled="busy">保存状态</button></form></div>
  </div>
</template>
